# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'football stats analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1754, 1039)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 209, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(180, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(870, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(640, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(410, 10, 231, 71))
        self.textBrowser_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 10, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(20, 80, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_10.setFont(font)
        self.textBrowser_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.KeyP_tier_forwards = QtWidgets.QTextBrowser(self.centralwidget)
        self.KeyP_tier_forwards.setGeometry(QtCore.QRect(640, 150, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.KeyP_tier_forwards.setFont(font)
        self.KeyP_tier_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyP_tier_forwards.setObjectName("KeyP_tier_forwards")
        self.Drib_tier_forwards = QtWidgets.QTextBrowser(self.centralwidget)
        self.Drib_tier_forwards.setGeometry(QtCore.QRect(870, 150, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Drib_tier_forwards.setFont(font)
        self.Drib_tier_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Drib_tier_forwards.setObjectName("Drib_tier_forwards")
        self.xG_tier_forwards = QtWidgets.QTextBrowser(self.centralwidget)
        self.xG_tier_forwards.setGeometry(QtCore.QRect(180, 150, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xG_tier_forwards.setFont(font)
        self.xG_tier_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.xG_tier_forwards.setMarkdown("")
        self.xG_tier_forwards.setObjectName("xG_tier_forwards")
        self.Shots_tier_forwards = QtWidgets.QTextBrowser(self.centralwidget)
        self.Shots_tier_forwards.setGeometry(QtCore.QRect(410, 150, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Shots_tier_forwards.setFont(font)
        self.Shots_tier_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Shots_tier_forwards.setObjectName("Shots_tier_forwards")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_15.setGeometry(QtCore.QRect(20, 150, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_15.setFont(font)
        self.textBrowser_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.Final_forwards = QtWidgets.QTextBrowser(self.centralwidget)
        self.Final_forwards.setGeometry(QtCore.QRect(180, 220, 1151, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Final_forwards.setFont(font)
        self.Final_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Final_forwards.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Final_forwards.setObjectName("Final_forwards")
        self.KeyP_tier_midfield = QtWidgets.QTextBrowser(self.centralwidget)
        self.KeyP_tier_midfield.setGeometry(QtCore.QRect(180, 460, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.KeyP_tier_midfield.setFont(font)
        self.KeyP_tier_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyP_tier_midfield.setObjectName("KeyP_tier_midfield")
        self.textBrowser_19 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_19.setGeometry(QtCore.QRect(20, 460, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_19.setFont(font)
        self.textBrowser_19.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.textBrowser_20 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_20.setGeometry(QtCore.QRect(870, 320, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_20.setFont(font)
        self.textBrowser_20.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_20.setObjectName("textBrowser_20")
        self.textBrowser_21 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_21.setGeometry(QtCore.QRect(180, 320, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_21.setFont(font)
        self.textBrowser_21.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_21.setObjectName("textBrowser_21")
        self.Disp_tier_midfield = QtWidgets.QTextBrowser(self.centralwidget)
        self.Disp_tier_midfield.setGeometry(QtCore.QRect(870, 460, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Disp_tier_midfield.setFont(font)
        self.Disp_tier_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Disp_tier_midfield.setObjectName("Disp_tier_midfield")
        self.textBrowser_26 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_26.setGeometry(QtCore.QRect(410, 320, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_26.setFont(font)
        self.textBrowser_26.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_26.setObjectName("textBrowser_26")
        self.textBrowser_27 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_27.setGeometry(QtCore.QRect(640, 320, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_27.setFont(font)
        self.textBrowser_27.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_27.setObjectName("textBrowser_27")
        self.textBrowser_28 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_28.setGeometry(QtCore.QRect(20, 320, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textBrowser_28.setFont(font)
        self.textBrowser_28.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_28.setObjectName("textBrowser_28")
        self.Final_midfield = QtWidgets.QTextBrowser(self.centralwidget)
        self.Final_midfield.setGeometry(QtCore.QRect(180, 530, 1151, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Final_midfield.setFont(font)
        self.Final_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Final_midfield.setObjectName("Final_midfield")
        self.Drib_tier_midfield = QtWidgets.QTextBrowser(self.centralwidget)
        self.Drib_tier_midfield.setGeometry(QtCore.QRect(640, 460, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Drib_tier_midfield.setFont(font)
        self.Drib_tier_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Drib_tier_midfield.setObjectName("Drib_tier_midfield")
        self.PassSuc_tier_midfield = QtWidgets.QTextBrowser(self.centralwidget)
        self.PassSuc_tier_midfield.setGeometry(QtCore.QRect(410, 460, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PassSuc_tier_midfield.setFont(font)
        self.PassSuc_tier_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PassSuc_tier_midfield.setObjectName("PassSuc_tier_midfield")
        self.textBrowser_32 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_32.setGeometry(QtCore.QRect(20, 390, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_32.setFont(font)
        self.textBrowser_32.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_32.setObjectName("textBrowser_32")
        self.Tackles_tier_defenders = QtWidgets.QTextBrowser(self.centralwidget)
        self.Tackles_tier_defenders.setGeometry(QtCore.QRect(180, 770, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Tackles_tier_defenders.setFont(font)
        self.Tackles_tier_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Tackles_tier_defenders.setObjectName("Tackles_tier_defenders")
        self.textBrowser_35 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_35.setGeometry(QtCore.QRect(20, 770, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_35.setFont(font)
        self.textBrowser_35.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_35.setObjectName("textBrowser_35")
        self.textBrowser_36 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_36.setGeometry(QtCore.QRect(870, 630, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_36.setFont(font)
        self.textBrowser_36.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_36.setObjectName("textBrowser_36")
        self.textBrowser_37 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_37.setGeometry(QtCore.QRect(180, 630, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_37.setFont(font)
        self.textBrowser_37.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_37.setObjectName("textBrowser_37")
        self.LongB_tier_defenders = QtWidgets.QTextBrowser(self.centralwidget)
        self.LongB_tier_defenders.setGeometry(QtCore.QRect(870, 770, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LongB_tier_defenders.setFont(font)
        self.LongB_tier_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LongB_tier_defenders.setObjectName("LongB_tier_defenders")
        self.textBrowser_42 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_42.setGeometry(QtCore.QRect(410, 630, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_42.setFont(font)
        self.textBrowser_42.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_42.setObjectName("textBrowser_42")
        self.textBrowser_43 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_43.setGeometry(QtCore.QRect(640, 630, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_43.setFont(font)
        self.textBrowser_43.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_43.setObjectName("textBrowser_43")
        self.textBrowser_44 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_44.setGeometry(QtCore.QRect(20, 630, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textBrowser_44.setFont(font)
        self.textBrowser_44.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_44.setObjectName("textBrowser_44")
        self.Final_defenders = QtWidgets.QTextBrowser(self.centralwidget)
        self.Final_defenders.setGeometry(QtCore.QRect(180, 840, 1151, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Final_defenders.setFont(font)
        self.Final_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Final_defenders.setObjectName("Final_defenders")
        self.DribP_tier_defenders = QtWidgets.QTextBrowser(self.centralwidget)
        self.DribP_tier_defenders.setGeometry(QtCore.QRect(640, 770, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DribP_tier_defenders.setFont(font)
        self.DribP_tier_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DribP_tier_defenders.setObjectName("DribP_tier_defenders")
        self.Inter_tier_defenders = QtWidgets.QTextBrowser(self.centralwidget)
        self.Inter_tier_defenders.setGeometry(QtCore.QRect(410, 770, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Inter_tier_defenders.setFont(font)
        self.Inter_tier_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Inter_tier_defenders.setObjectName("Inter_tier_defenders")
        self.textBrowser_48 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_48.setGeometry(QtCore.QRect(20, 700, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_48.setFont(font)
        self.textBrowser_48.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_48.setObjectName("textBrowser_48")
        self.xG_forwards = QtWidgets.QTextEdit(self.centralwidget)
        self.xG_forwards.setGeometry(QtCore.QRect(180, 80, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.xG_forwards.setFont(font)
        self.xG_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.xG_forwards.setObjectName("xG_forwards")
        self.KeyP_forwards = QtWidgets.QTextEdit(self.centralwidget)
        self.KeyP_forwards.setGeometry(QtCore.QRect(640, 80, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.KeyP_forwards.setFont(font)
        self.KeyP_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyP_forwards.setObjectName("KeyP_forwards")
        self.Shots_forwards = QtWidgets.QTextEdit(self.centralwidget)
        self.Shots_forwards.setGeometry(QtCore.QRect(410, 80, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Shots_forwards.setFont(font)
        self.Shots_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Shots_forwards.setObjectName("Shots_forwards")
        self.Drib_forwards = QtWidgets.QTextEdit(self.centralwidget)
        self.Drib_forwards.setGeometry(QtCore.QRect(870, 80, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Drib_forwards.setFont(font)
        self.Drib_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Drib_forwards.setObjectName("Drib_forwards")
        self.Drib_midfield = QtWidgets.QTextEdit(self.centralwidget)
        self.Drib_midfield.setGeometry(QtCore.QRect(640, 390, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Drib_midfield.setFont(font)
        self.Drib_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Drib_midfield.setObjectName("Drib_midfield")
        self.KeyP_midfield = QtWidgets.QTextEdit(self.centralwidget)
        self.KeyP_midfield.setGeometry(QtCore.QRect(180, 390, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.KeyP_midfield.setFont(font)
        self.KeyP_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyP_midfield.setObjectName("KeyP_midfield")
        self.PassSuc_midfield = QtWidgets.QTextEdit(self.centralwidget)
        self.PassSuc_midfield.setGeometry(QtCore.QRect(410, 390, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PassSuc_midfield.setFont(font)
        self.PassSuc_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PassSuc_midfield.setObjectName("PassSuc_midfield")
        self.Disp_midfield = QtWidgets.QTextEdit(self.centralwidget)
        self.Disp_midfield.setGeometry(QtCore.QRect(870, 390, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Disp_midfield.setFont(font)
        self.Disp_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Disp_midfield.setObjectName("Disp_midfield")
        self.DribP_defenders = QtWidgets.QTextEdit(self.centralwidget)
        self.DribP_defenders.setGeometry(QtCore.QRect(640, 700, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DribP_defenders.setFont(font)
        self.DribP_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DribP_defenders.setObjectName("DribP_defenders")
        self.Tackles_defenders = QtWidgets.QTextEdit(self.centralwidget)
        self.Tackles_defenders.setGeometry(QtCore.QRect(180, 700, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Tackles_defenders.setFont(font)
        self.Tackles_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Tackles_defenders.setObjectName("Tackles_defenders")
        self.Inter_defenders = QtWidgets.QTextEdit(self.centralwidget)
        self.Inter_defenders.setGeometry(QtCore.QRect(410, 700, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Inter_defenders.setFont(font)
        self.Inter_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Inter_defenders.setObjectName("Inter_defenders")
        self.LongB_defenders = QtWidgets.QTextEdit(self.centralwidget)
        self.LongB_defenders.setGeometry(QtCore.QRect(870, 700, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LongB_defenders.setFont(font)
        self.LongB_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LongB_defenders.setObjectName("LongB_defenders")
        self.textBrowser_22 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_22.setGeometry(QtCore.QRect(1100, 320, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_22.setFont(font)
        self.textBrowser_22.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_22.setObjectName("textBrowser_22")
        self.Disp_tier_forwards = QtWidgets.QTextBrowser(self.centralwidget)
        self.Disp_tier_forwards.setGeometry(QtCore.QRect(1100, 150, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Disp_tier_forwards.setFont(font)
        self.Disp_tier_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Disp_tier_forwards.setObjectName("Disp_tier_forwards")
        self.LongB_tier_midfield = QtWidgets.QTextBrowser(self.centralwidget)
        self.LongB_tier_midfield.setGeometry(QtCore.QRect(1100, 460, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LongB_tier_midfield.setFont(font)
        self.LongB_tier_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LongB_tier_midfield.setObjectName("LongB_tier_midfield")
        self.textBrowser_33 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_33.setGeometry(QtCore.QRect(1100, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_33.setFont(font)
        self.textBrowser_33.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_33.setObjectName("textBrowser_33")
        self.Aerial_tier_defenders = QtWidgets.QTextBrowser(self.centralwidget)
        self.Aerial_tier_defenders.setGeometry(QtCore.QRect(1100, 770, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Aerial_tier_defenders.setFont(font)
        self.Aerial_tier_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Aerial_tier_defenders.setObjectName("Aerial_tier_defenders")
        self.textBrowser_39 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_39.setGeometry(QtCore.QRect(1100, 630, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textBrowser_39.setFont(font)
        self.textBrowser_39.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser_39.setObjectName("textBrowser_39")
        self.Disp_forwards = QtWidgets.QTextEdit(self.centralwidget)
        self.Disp_forwards.setGeometry(QtCore.QRect(1100, 80, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Disp_forwards.setFont(font)
        self.Disp_forwards.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Disp_forwards.setObjectName("Disp_forwards")
        self.LongB_midfield = QtWidgets.QTextEdit(self.centralwidget)
        self.LongB_midfield.setGeometry(QtCore.QRect(1100, 390, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LongB_midfield.setFont(font)
        self.LongB_midfield.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LongB_midfield.setObjectName("LongB_midfield")
        self.Aerial_defenders = QtWidgets.QTextEdit(self.centralwidget)
        self.Aerial_defenders.setGeometry(QtCore.QRect(1100, 700, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Aerial_defenders.setFont(font)
        self.Aerial_defenders.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Aerial_defenders.setObjectName("Aerial_defenders")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 920, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 920, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 920, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(710, 920, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(950, 920, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 950, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 950, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(490, 950, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(720, 950, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(960, 950, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1470, 620, 271, 291))
        self.label_11.setMinimumSize(QtCore.QSize(271, 181))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../../Users/Khaopoon/OneDrive/Pictures/Saved Pictures/football.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1440, 100, 301, 391))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../../Users/Khaopoon/OneDrive/Pictures/Saved Pictures/football_pitch2.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">xG Per90</p></body></html>"))
        self.textBrowser_3.setMarkdown(_translate("MainWindow", "Dribbles Per90\n"
"\n"
""))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dribbles Per90</p></body></html>"))
        self.textBrowser_4.setMarkdown(_translate("MainWindow", "KeyP Per90\n"
"\n"
""))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">KeyP Per90</p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Shots Per90 </span></p></body></html>"))
        self.textBrowser.setMarkdown(_translate("MainWindow", "Forwards\n"
"\n"
""))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Forwards</p></body></html>"))
        self.textBrowser_10.setMarkdown(_translate("MainWindow", "Player Stats\n"
"\n"
""))
        self.textBrowser_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Player Stats</p></body></html>"))
        self.KeyP_tier_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.Drib_tier_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.xG_tier_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Shots_tier_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Player Tier</p></body></html>"))
        self.Final_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.KeyP_tier_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_19.setMarkdown(_translate("MainWindow", "Player Tier\n"
"\n"
""))
        self.textBrowser_19.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Player Tier</p></body></html>"))
        self.textBrowser_20.setMarkdown(_translate("MainWindow", "Disp Per90\n"
"\n"
""))
        self.textBrowser_20.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Disp Per90</p></body></html>"))
        self.textBrowser_21.setMarkdown(_translate("MainWindow", "KeyP Per90\n"
"\n"
""))
        self.textBrowser_21.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">KeyP Per90</p></body></html>"))
        self.Disp_tier_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_26.setMarkdown(_translate("MainWindow", "PassSuc %\n"
"\n"
""))
        self.textBrowser_26.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PassSuc %</p></body></html>"))
        self.textBrowser_27.setMarkdown(_translate("MainWindow", "Dribbles Per90\n"
"\n"
""))
        self.textBrowser_27.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dribbles Per90</p></body></html>"))
        self.textBrowser_28.setMarkdown(_translate("MainWindow", "Midfielders\n"
"\n"
""))
        self.textBrowser_28.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Midfielders</p></body></html>"))
        self.Final_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Drib_tier_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.PassSuc_tier_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_32.setMarkdown(_translate("MainWindow", "Player Stats\n"
"\n"
""))
        self.textBrowser_32.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Player Stats</p></body></html>"))
        self.Tackles_tier_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_35.setMarkdown(_translate("MainWindow", "Player Tier\n"
"\n"
""))
        self.textBrowser_35.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Player Tier</p></body></html>"))
        self.textBrowser_36.setMarkdown(_translate("MainWindow", "LongB Per90\n"
"\n"
""))
        self.textBrowser_36.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LongB Per90</p></body></html>"))
        self.textBrowser_37.setMarkdown(_translate("MainWindow", "Tackles Per90\n"
"\n"
""))
        self.textBrowser_37.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Tackles Per90</p></body></html>"))
        self.LongB_tier_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_42.setMarkdown(_translate("MainWindow", "Inter Per90\n"
"\n"
""))
        self.textBrowser_42.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Inter Per90</p></body></html>"))
        self.textBrowser_43.setMarkdown(_translate("MainWindow", "DribbledP Per90\n"
"\n"
""))
        self.textBrowser_43.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DribbledP Per90</p></body></html>"))
        self.textBrowser_44.setMarkdown(_translate("MainWindow", "Defenders\n"
"\n"
""))
        self.textBrowser_44.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Defenders</p></body></html>"))
        self.Final_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.DribP_tier_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.Inter_tier_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_48.setMarkdown(_translate("MainWindow", "Player Stats\n"
"\n"
""))
        self.textBrowser_48.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Player Stats</p></body></html>"))
        self.xG_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.KeyP_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.Shots_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.Drib_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.Drib_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.KeyP_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.PassSuc_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.Disp_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.DribP_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.Tackles_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.Inter_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.LongB_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_22.setMarkdown(_translate("MainWindow", "LongB Per90\n"
"\n"
""))
        self.textBrowser_22.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">LongB Per90</p></body></html>"))
        self.Disp_tier_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.LongB_tier_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_33.setMarkdown(_translate("MainWindow", "Disp Per90\n"
"\n"
""))
        self.textBrowser_33.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Disp Per90</p></body></html>"))
        self.Aerial_tier_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_39.setMarkdown(_translate("MainWindow", "AerialDW Per90\n"
"\n"
""))
        self.textBrowser_39.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:9px; margin-bottom:9px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">AerialDW Per90</p></body></html>"))
        self.Disp_forwards.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.LongB_midfield.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.Aerial_defenders.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "xG Per90: Expected Goal per 90 mins"))
        self.label_2.setText(_translate("MainWindow", "Shots Per90: Shots per 90 mins"))
        self.label_3.setText(_translate("MainWindow", "KeyP Per90: Key Passes per 90 mins"))
        self.label_4.setText(_translate("MainWindow", "Dribbles Per90: Dribbles per 90 mins"))
        self.label_5.setText(_translate("MainWindow", "Disp Per90: Dispossessed per 90 mins"))
        self.label_6.setText(_translate("MainWindow", "PassSuc %: Pass Success Percentage"))
        self.label_7.setText(_translate("MainWindow", "LongB Per90: Long Balls per 90 mins"))
        self.label_8.setText(_translate("MainWindow", "Tackles Per90: Tackles per 90 mins"))
        self.label_9.setText(_translate("MainWindow", "Inter Per90: Interceptions per 90 mins"))
        self.label_10.setText(_translate("MainWindow", "AerialDW Per90: Aerial Duels won per 90 mins"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
